### ISSUE TITLE
Use UTF-8 as default locale

### ISSUE THREAD

**Issue by lubo** [Starefossen/docker-ruby-node#1]
It seems like the images are not using UTF-8.

**Comment by radeno** [comment]
What do you mean? Could you explain it?
This image just combine official Ruby and Node images

**Comment by lubo** [comment]
If I remember correctly, `LC_ALL` is not set and therefore UTF-8 is not used.

**Comment by radeno** [comment]
You are right. Official Debian Jessie repository set locale as POSIX.
Many users could use Ruby or Node console and they probably need unicode. We should change it to C.UTF-8.
@Starefossen what do you think?

**Comment by Starefossen** [comment]
I personally believe that UTF-8 is the right direction to go, not sure what implications this will have for existing Ruby users?

**Comment by radeno** [comment]
There was some discussions about it. https://github.com/docker-library/ruby/search?q=utf-8&type=Issues&utf8=✓
I don't really know why this wasn't implement yet. It is about unicode characters in console. For me as a central european guy is unicode a right way.
Debian have preinstalled utf-8 https://github.com/docker-library/docs/tree/master/debian#locales We can change it. I don't know about Alpine.

**Comment by radeno** [comment]
#4

**Comment by radeno** [comment]
Changed to C.UTF-8 for Debian images.
