### ISSUE TITLE
Would it be possible to peg Ruby and Node to the specific version?

### ISSUE THREAD

**Issue by ndbroadbent** [Starefossen/docker-ruby-node#15]
I'm using your image with GitLab CI, and would like to peg Ruby and Node to the current version.

I'm looking at the [tags](https://hub.docker.com/r/starefossen/ruby-node/tags/) page on `hub.docker.com`, and it looks like you only release a few very generic versions. (e.g. `2-8` for Ruby 2.x.x and Node 8.x.x).

Would it be possible to release a more specific tag for the current version? E.g. `2.4.2-8.6.0`?

I'd like to use something like `image: "starefossen/ruby-node:2.4.2-8.6.0"` in my `.gitlab-ci.yml`, so that I have a consistent environment.

**Comment by ndbroadbent** [comment]
Never mind! I figured out how to push my own docker image to hub.docker.com. Thanks for the Dockerfile!

**Comment by radeno** [comment]
👍 Custom image is way. More image combinations cause more time to get them update. It takes much time. I think mayor versions are enough.

**Comment by arashm** [comment]
This is actually what I need too, a guaranty that I'm always running the tests with the versions similar to the production environment. I really think this should have stayed open.

**Comment by radeno** [comment]
That could be fine but we don't have so time to maintain 24 combinations of Ruby 2 (2.0 to 2.4) and Node 8 (8.0 to 8.6) and 44 combinations of Ruby 2 and Node 6 for one Linux repository. There are 3 distributions (Full, Slim and Alpine) so in final 204 images :)

Mayor version is enough. When is minor version of Ruby or Node published we always update.
Minor versions are almost compatible with other lower minor versions.
