### ISSUE TITLE
Add Yarn

### ISSUE THREAD

**Issue by radeno** [Starefossen/docker-ruby-node#2]
Yarn is nowadays de-factor standard to install Node packages.
So it will be nice to have it pre-installed in docker image.

Default node docker image use it
https://github.com/nodejs/docker-node/blob/master/6.10/Dockerfile

**Comment by radeno** [comment]
Pull request #3

**Comment by Starefossen** [comment]
Thanks a lot Radovan for solid effort 💯

**Comment by Starefossen** [comment]
I have added you as an official collaborator of this project!

**Comment by radeno** [comment]
You are welcome.
For Rails 5.1 with Webpack support is this docker image highly required :)
