### ISSUE TITLE
Outdated README Node Versions

### ISSUE THREAD

**Issue by colinking** [Starefossen/docker-ruby-node#26]
Consider updating (or removing) the note on which version of Node is used, since it is outdated now.

[Looks like](https://nodejs.org/dist/index.tab) 2-8 uses `v8.11.2` and 2-6 uses `v6.14.2`

**Comment by radeno** [comment]
We have waiting pull request where is notice about possible misstatement in Readme.

https://github.com/Starefossen/docker-ruby-node/pull/24/files#diff-04c6e90faac2675aa89e2176d2eec7d8R5

**Comment by radeno** [comment]
Merged
