### ISSUE TITLE
Any chance of a yarn update to at least 10.0.1?

### ISSUE THREAD

**Issue by EdwardIII** [Starefossen/docker-ruby-node#33]
In the node10 build we see this error:

    (node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

According to this issue, `yarn 10.0.1` fixes this: https://github.com/yarnpkg/yarn/issues/5770#issuecomment-427755306

I see in your Dockerfile that it always installs the current version. Would you mind kicking off another build so this gets updated?

Thanks!

**Comment by pokonski** [comment]
That'd be great as I am running into the same issue

**Comment by radeno** [comment]
@EdwardIII it is required to rebuild images on dockerhub. cc @Starefossen

**Comment by radeno** [comment]
Or use my rebuilded fork https://hub.docker.com/r/smikino/ruby-node/tags/
it is from multistage pull request
