### ISSUE TITLE
Ruby version outdated

### ISSUE THREAD

**Issue by ruswerner** [Starefossen/docker-ruby-node#34]
I am getting an old version of Ruby using this image. When I pull the base image directly it's using 2.5.3, which is the version our gemfile is locked to...

    $ docker pull starefossen/ruby-node:2-8
    $ docker run -it starefossen/ruby-node:2-8 bash -c "ruby -v"
    ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

    $ docker pull ruby:2-stretch
    $ docker run -it ruby:2-stretch bash -c "ruby -v"
    ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

How can I resolve this?

**Comment by radeno** [comment]
@ruswerner without rebuilding in DockerHub you have just one solution, make it own. Look at my fork https://github.com/radeno/docker-ruby-node/tree/multistage it is simple to copy that.
Till then we will wait for @Starefossen  reply.

**Comment by radeno** [comment]
Or use my rebuilded fork https://hub.docker.com/r/smikino/ruby-node/tags/
it is from multistage pull request

**Comment by ruswerner** [comment]
@radeno Thanks! We ended up just using `ruby:2-stretch` and `mini_racer` to compile assets.
