### ISSUE TITLE
Possibility of remove Node 4

### ISSUE THREAD

**Issue by radeno** [Starefossen/docker-ruby-node#5]
What about Node 4?

Support is still active till april of 2018.
Anyway is necessary to support this dying version? By download numbers from https://nodesource.com/node-by-numbers was by end of year 2016 almost half smaller than version 6. Half year before (July 2016) was version 4 almost three times larger!
It is strong assumption that nowadays is used very rarely.

Node 4 can be still accessible from Docker Hub repository. But unmaintaned.

OT:
On Docker Hub is probably defined tag 2-6-alpine twice. https://hub.docker.com/r/starefossen/ruby-node/builds/ 
![screen shot 2017-05-23 at 12 29 33](https://cloud.githubusercontent.com/assets/58521/26350487/a86fa3ae-3fb3-11e7-831a-9e3dcf2a4ac7.png)

**Comment by Starefossen** [comment]
I agree! Lets get ride of it from git, and as you mention, the tags will remain available on Docker Hub. 

Do you have a Docker Hub user so I can give you access to managing the tags setup over there?

**Comment by radeno** [comment]
Docker hub name: smikino

**Comment by Starefossen** [comment]
Thanks, added 😄

**Comment by radeno** [comment]
#6 merged
